import { Project, BlogPost } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'curecancer-ucl',
    title: 'CureCancer@UCL',
    year: '2024',
    category: 'Website Design & SEO',
    bgColor: '#ff6200',
    textColor: '#000000',
    image: 'assets/curecancerucl-device.jpeg',
    description: 'Full website redesign and local SEO campaign for a Dover-based kitchen fitting company. New site launched with location pages targeting East Kent, resulting in a significant increase in organic enquiries within the first quarter.',
  },
  {
    id: '2',
    slug: 'hamilton-nexus',
    title: 'Hamilton Nexus',
    year: '2024',
    category: 'Branding & Web Design',
    bgColor: '#ffffff',
    textColor: '#1f00ff',
    image: 'assets/hamilton-nexus-device.jpeg',
    description: 'Complete rebrand and website build for a Canterbury plumbing and heating company. Delivered logo, brand guidelines, vehicle livery design, and a conversion-focused website with integrated booking.',
  },
  {
    id: '3',
    slug: 'jcas-pds',
    title: 'JCAS P&Ds',
    year: '2024',
    category: 'Paid Ads & Design',
    bgColor: '#2e3538',
    textColor: '#b3ffcb',
    image: 'assets/jcas-device.jpeg',
    description: 'Paid advertising and graphic design for a Thanet food delivery service. Built Meta ad campaigns targeting Margate, Ramsgate, and Broadstairs with custom creative that reduced cost per order acquisition.',
  },
  {
    id: '4',
    slug: 'me-stewart',
    title: 'M.E. Stewart Building Contractors LTD',
    year: '2024',
    category: 'Web Design & Local SEO',
    bgColor: '#ffc400',
    textColor: '#3d3b54',
    image: 'assets/mestewart-device.jpeg',
    description: 'Website design and local SEO for a Deal-based wellness clinic. Built location-specific landing pages for Deal, Dover, and Canterbury that rank in the local map pack for key treatment searches.',
  },
  {
    id: '5',
    slug: 'sos-electrical',
    title: 'SOS Electrical LTD',
    year: '2023',
    category: 'Branding & Google Ads',
    bgColor: '#333333',
    textColor: '#949494',
    image: 'assets/soselec-device.jpeg',
    description: 'Brand identity and Google Ads management for an independent garage in Kent. Designed full visual identity and launched search campaigns targeting MOT, servicing, and repair keywords across East Kent postcodes.',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Why Kent Businesses Need Local SEO in 2024',
    date: 'Jan 12, 2024',
    link: '/services/local-seo',
  },
  {
    id: '2',
    title: 'How a Fast Website Directly Increases Your Conversion Rate',
    date: 'Dec 5, 2023',
    link: '/services/website-design',
  },
  {
    id: '3',
    title: 'Google Ads vs Meta Ads: Which Is Right for Your Business?',
    date: 'Nov 18, 2023',
    link: '/services/paid-ads',
  },
];
