import { Project, BlogPost } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'curecancer-ucl',
    title: 'CureCancer@UCL',
    year: '2025',
    category: 'Website Design & SEO',
    bgColor: '#E91E63',
    textColor: '#000000',
    image: 'assets/curecancerucl-device.jpeg',
    description: 'This was a full website takeover from their previous provider, we stepped in to assist the charity in gaining a stronger online presence and achieving higher donation rates, not our typical client but has been a pleasure to build alongside them.',
  },
  {
    id: '2',
    slug: 'hamilton-nexus',
    title: 'Hamilton Nexus',
    year: '2025',
    category: 'Branding & Web Design',
    bgColor: '#A30E15',
    textColor: '#1f00ff',
    image: 'assets/hamilton-nexus-device.jpeg',
    description: 'Full Website rebuild for a construction recruitment agency in London. Built out using a start from scratch method, carrying assets over from their current site an implementing them in a refreshing look. Paired with a CMS Dashboard to handle candidate enquiries.',
  },
  {
    id: '3',
    slug: 'jcas-pds',
    title: 'JCAS P&Ds',
    year: '2025',
    category: 'Paid Ads & Design',
    bgColor: '#0F3D2E',
    textColor: '#b3ffcb',
    image: 'assets/jcas-device.jpeg',
    description: 'Full website build for a start-up Painting and decorating company based in Deal, Kent. This was a start from scratch with 0 online presence to a full website build to get enquiries firing through in just 2 days.',
  },
  {
    id: '4',
    slug: 'me-stewart',
    title: 'M.E. Stewart Building Contractors LTD',
    year: '2025',
    category: 'Web Design & Local SEO',
    bgColor: '#004AAD',
    textColor: '#3d3b54',
    image: 'assets/mestewart-device.jpeg',
    description: 'Full website build, Mark Stewart from M.E. Stewart Building Contractors LTD had never had a website before and wanted a lead engine to scale his construction company in local areas such as Deal, Kent. This website has boosted his online presence massively and also got him ranking between 1st & 3rd in multiple local areas.',
  },
  {
    id: '5',
    slug: 'sos-electrical',
    title: 'SOS Electrical LTD',
    year: '2023',
    category: 'Branding & Google Ads',
    bgColor: '#1E293B',
    textColor: '#949494',
    image: 'assets/soselec-device.jpeg',
    description: 'This was a full website build for a new Electrician start-up based in Essex. This website was built from nothing with full Branding, Graphic Design and SEO to dominate local search.',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Why Kent Businesses Need Local SEO in 2024',
    date: 'Jan 12, 2024',
    link: '/services/local-seo',
  },
  {
    id: '2',
    title: 'How a Fast Website Directly Increases Your Conversion Rate',
    date: 'Dec 5, 2023',
    link: '/services/website-design',
  },
  {
    id: '3',
    title: 'Google Ads vs Meta Ads: Which Is Right for Your Business?',
    date: 'Nov 18, 2023',
    link: '/services/paid-ads',
  },
];
